---
# Unit test GitHub Action configuration file
name: UnitTests

on:
  - pull_request

jobs:
  preview:
    name: UnitTest
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root
      - name: Run tests with pytest
        run: |
          if [ -d tests ]; then pytest tests -vv; fi
